-- setMode  (not implemented yet)
--
-- Enter Live / Enter Practice: apply the full configuration of the mode and
-- store it in project ext state. Refused while recording.
--
--   setting              live                    practice
--   [Show] tracks        unmuted                 muted
--   [Practice] tracks    muted                   unmuted
--   master playrate      1.0                     practice rate
--   preserve pitch       (any)                   on
--   record mode          normal                  time-selection auto-punch
--   [Live] tracks        all armed, unmuted      chosen players armed, others disarmed;
--                                                player mutes applied
--   record path          Recordings/Live         Recordings/Practice
--
-- args:    { mode = "live" | "practice" }
-- returns: { mode }
--
-- REAPER API: SetMediaTrackInfo_Value (B_MUTE, I_RECARM), CSurf_OnPlayRateChange,
--             Main_OnCommand (record mode, preserve pitch toggles),
--             GetSetProjectInfo_String ("RECORD_PATH"), SetProjExtState
